# Generated by Django 4.1.5 on 2023-10-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(default='No_name', max_length=255),
            preserve_default=False,
        ),
    ]
