# Generated by Django 4.2.6 on 2023-10-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20231023_2356'),
        ('cartbook', '0002_delete_book_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('carts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartbook.cart')),
            ],
        ),
    ]
