# Generated by Django 4.2.4 on 2023-10-27 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartbook', '0003_book_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_cart',
            name='subtotal',
            field=models.IntegerField(default=0),
        ),
    ]
