# Generated by Django 4.2.5 on 2023-10-27 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0002_alter_nota_date'),
        ('cartbook', '0004_book_cart_nota_alter_book_cart_carts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_cart',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkoutbook.nota'),
        ),
    ]
