# Generated by Django 4.2.4 on 2023-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartbook', '0004_book_cart_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_cart',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
