# Generated by Django 4.2.5 on 2023-10-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartbook', '0005_alter_book_cart_nota'),
        ('cartbook', '0005_book_cart_notes'),
    ]

    operations = [
    ]
