# Generated by Django 4.2.5 on 2023-10-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartbook', '0006_merge_0005_alter_book_cart_nota_0005_book_cart_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_cart',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
