# Generated by Django 4.2.4 on 2023-10-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_book', models.CharField(max_length=255)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('isbn', models.CharField(max_length=10)),
                ('publisher', models.TextField()),
                ('year', models.IntegerField()),
                ('author', models.TextField()),
                ('stocks', models.IntegerField()),
            ],
        ),
    ]
