# Generated by Django 4.2.4 on 2023-10-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link_image',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
