# Generated by Django 4.2.4 on 2023-10-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_book_link_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='link_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name_book',
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
