# Generated by Django 4.2.5 on 2023-10-27 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 27, 3, 54, 4, 727453, tzinfo=datetime.timezone.utc)),
        ),
    ]
