# Generated by Django 4.2.5 on 2023-10-27 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0002_alter_nota_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='alamat',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='nota',
            name='metode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 27, 18, 19, 30, 670555, tzinfo=datetime.timezone.utc)),
        ),
    ]
