# Generated by Django 4.2.5 on 2023-10-29 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0005_rename_metode_nota_layanan_alter_nota_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 29, 14, 26, 59, 437435, tzinfo=datetime.timezone.utc)),
        ),
    ]
