# Generated by Django 4.2.4 on 2023-10-29 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0008_alter_nota_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 29, 16, 12, 20, 329123, tzinfo=datetime.timezone.utc)),
        ),
    ]
