# Generated by Django 4.2.5 on 2023-10-29 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0009_alter_nota_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 29, 16, 38, 20, 837958, tzinfo=datetime.timezone.utc)),
        ),
    ]
