# Generated by Django 4.1.5 on 2023-10-31 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0011_alter_nota_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 31, 7, 45, 32, 457746, tzinfo=datetime.timezone.utc)),
        ),
    ]
