# Generated by Django 4.1.5 on 2023-12-18 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0012_alter_nota_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 18, 3, 15, 11, 408078, tzinfo=datetime.timezone.utc)),
        ),
    ]
