# Generated by Django 4.2.4 on 2023-11-22 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0013_alter_nota_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 22, 6, 15, 42, 558356, tzinfo=datetime.timezone.utc)),
        ),
    ]
