# Generated by Django 4.2.5 on 2023-11-27 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0014_alter_nota_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 9, 6, 57, 642210, tzinfo=datetime.timezone.utc)),
        ),
    ]
