# Generated by Django 4.1.5 on 2023-12-04 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkoutbook', '0016_alter_nota_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 4, 9, 12, 3, 388439, tzinfo=datetime.timezone.utc)),
        ),
    ]
